site_name: LetzElPhC
site_description: "A complementary C code for Yambo to compute electron-phonon coupling"
site_author: Muralidhar Nalabothula 

# Important for project pages hosted under /repo/
site_url: https://muralidhar-nalabothula.github.io/LetzElPhC/

# Theme configuration
theme:
  name: material
  # logo: images/logo.png
  language: en
  palette:
    primary: black 
    accent: grey
  font:
    text: Helvetica
    code: Roboto Mono  # or keep monospace
  features:
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

# Plugins
plugins:
  - search:
      lang: en
      prebuild_index: true
  - git-revision-date-localized:    # shows last updated timestamp
      fallback_to_build_date: false
      locale: en
  - minify:
      minify_html: true             # optional for smaller output size

# Extra JavaScript / CSS
extra_css:
  - 'css/custom.css'     # add custom styles
extra_javascript:
  - 'js/custom.js'       # add custom JS if needed

# Repository integration (adds "Edit on GitHub" links)
repo_url: https://github.com/muralidhar-nalabothula/LetzElPhC
repo_name: GitHub

# Markdown extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed

copyright: "Â© 2025 Muralidhar Nalabothula"
extra:
    generator: false

# # Navigation structure
# nav:
#   - Home: index.md
#   - Installing the Code: installing.md
#   - Running the Code: running.md
#   # - API Reference: api.md
#   # - FAQ: faq.md
#   # - Changelog: changelog.md
#
nav:
  - Home: index.md
  - Getting started:
    - Installation: installing.md
    - Running the Code: running.md
    - License: license.md
    # - Tutorials:
    #   - tutorials/index.md
    #   - "Blogs":
    #     - tutorials/blogs/basic.md
    #     - tutorials/blogs/navigation.md
    #     - tutorials/blogs/engage.md
    #   - "Social cards":
    #     - tutorials/social/basic.md
    #     - tutorials/social/custom.md
    # - Changelog:
    #   - changelog/index.md
    #   - How to upgrade: upgrade.md
  # - Tutorials:
  #   - setup/index.md
  #   - Changing the colors: setup/changing-the-colors.md
  #   - Changing the fonts: setup/changing-the-fonts.md
  #   - Changing the language: setup/changing-the-language.md
  #   - Changing the logo and icons: setup/changing-the-logo-and-icons.md
  #   - Ensuring data privacy: setup/ensuring-data-privacy.md
  #   - Setting up navigation: setup/setting-up-navigation.md
  #   - Setting up site search: setup/setting-up-site-search.md
  #   - Setting up site analytics: setup/setting-up-site-analytics.md
  #   - Setting up social cards: setup/setting-up-social-cards.md
  #   - Setting up a blog: setup/setting-up-a-blog.md
  #   - Setting up tags: setup/setting-up-tags.md
  #   - Setting up versioning: setup/setting-up-versioning.md
  #   - Setting up the header: setup/setting-up-the-header.md
  #   - Setting up the footer: setup/setting-up-the-footer.md
  #   - Adding a git repository: setup/adding-a-git-repository.md
  #   - Adding a comment system: setup/adding-a-comment-system.md
  #   - Building an optimized site: setup/building-an-optimized-site.md
  #   - Building for offline usage: setup/building-for-offline-usage.md
  #   - Extensions:
  #     - setup/extensions/index.md
  #     - Python Markdown: setup/extensions/python-markdown.md
  #     - Python Markdown Extensions: setup/extensions/python-markdown-extensions.md
  # - Plugins:
  #   - plugins/index.md
  #   - Blog: plugins/blog.md
  #   - Group: plugins/group.md
  #   - Info: plugins/info.md
  #   - Meta: plugins/meta.md
  #   - Offline: plugins/offline.md
  #   - Optimize: plugins/optimize.md
  #   - Privacy: plugins/privacy.md
  #   - Projects: plugins/projects.md
  #   - Search: plugins/search.md
  #   - Social: plugins/social.md
  #   - Tags: plugins/tags.md
  #   - Typeset: plugins/typeset.md
  #   - Requirements:
  #     - Image processing: plugins/requirements/image-processing.md
  #     - Caching: plugins/requirements/caching.md
  # - Reference:
  #   - reference/index.md
  #   - Admonitions: reference/admonitions.md
    # - Annotations: reference/annotations.md
    # - Buttons: reference/buttons.md
    # - Code blocks: reference/code-blocks.md
    # - Content tabs: reference/content-tabs.md
    # - Data tables: reference/data-tables.md
    # - Diagrams: reference/diagrams.md
    # - Footnotes: reference/footnotes.md
    # - Formatting: reference/formatting.md
    # - Grids: reference/grids.md
    # - Icons, Emojis: reference/icons-emojis.md
    # - Images: reference/images.md
    # - Lists: reference/lists.md
    # - Math: reference/math.md
    # - Tooltips: reference/tooltips.md
  # - Insiders:
    # - insiders/index.md
    # - Getting started: insiders/getting-started.md
    # - Changelog:
    #   - insiders/changelog/index.md
    #   - How to upgrade: insiders/upgrade.md
  # - Community:
    # - Contributing:
    #   - contributing/index.md
    #   - Reporting a bug: contributing/reporting-a-bug.md
    #   - Reporting a docs issue: contributing/reporting-a-docs-issue.md
    #   - Requesting a change: contributing/requesting-a-change.md
    #   - Adding translations: contributing/adding-translations.md
    #   - Making a pull request: contributing/making-a-pull-request.md
    #   - Asking a question: https://github.com/squidfunk/mkdocs-material/discussions
    # - Guides:
    #   - Creating a reproduction: guides/creating-a-reproduction.md
  # - Blog:
    # - blog/index.md
